### ISSUE TITLE
Investigate memory behavior of many non-streaming connections

### ISSUE THREAD

**Issue by FinleyMcIlwaine** [well-typed/grapesy#133]
During stress testing, we discovered that the memory profile of opening many connections and executing a single non-streaming RPC call results in strange memory behavior, especially relative to executing many non-streaming calls on a single connection. In particular, we see some closures relating to HPACK slowly pile up before reaching a constant heap residency of anywhere between 2M and 18M. (Exactly what this heap residency is depends on the RTS sample rate, strangely, but that's another can of worms that grapesy probably doesn't need to care about.)

<img width="936" alt="Screenshot 2024-04-10 at 11 48 02 AM" src="https://github.com/well-typed/grapesy/assets/43023876/33c8be31-ebdd-461c-92e8-ec2b15920fb8">

Each of the lines in the above chart marks 1000 new connections.

<img width="1361" alt="Screenshot 2024-04-10 at 11 48 54 AM" src="https://github.com/well-typed/grapesy/assets/43023876/a2b78f93-dd30-45de-9ba1-956cd22fbd5a">

Thankfully, the memory complexity still *appears* constant, but this is nonetheless worth investigating to see if we can reduce the residency.

Contrast this against doing the same number of calls on a single connection:

<img width="932" alt="Screenshot 2024-04-10 at 11 56 13 AM" src="https://github.com/well-typed/grapesy/assets/43023876/6bb26ad1-ac14-44bd-8878-46562e074640">

Much lower and more consistent residency.

# Reproduce

To reproduce, run the `test-stress` executable server and client:

```
cabal run test-stress -- server
```

```
cabal run test-stress -- client many-connections 10000 +RTS -s -l -olclient.eventlog -i0.01 -hi
```

Don't forget to enable `-finfo-table-map -fdistinct-constructor-tables` on at least `grapesy` and probably `http2`.

**Comment by edsko** [comment]
This is simply due to the connection window for each connection; decreasing the connection window decreases memory usage (but! we must be careful with the relationship between the connection window size, stream window size, and number of concurrent streams -- see https://github.com/well-typed/grapesy/issues/169#issuecomment-2203383858).
