### ISSUE TITLE
Make HTTP2 window size configurable

### ISSUE THREAD

**Issue by FinleyMcIlwaine** [well-typed/grapesy#145]
`http2` uses a default connection window size of [1MB per connection and 256KB per stream](https://github.com/kazu-yamamoto/http2/blob/b054a706efa40f1c4b3ee077f2ac509c19a29147/Network/HTTP2/Client/Run.hs#L56), which can cause data to pile up on a receiver's heap if they can't keep up. We've observed this in the stress tests. The standard fix for this is to reduce the window size. `http2` makes this configurable, although a brief test where we tried to reduce the window size on the client led to bus errors in the server. We should make this configurable in `grapesy` as well, and see if we can avoid/fix the bus errors.

**Comment by edsko** [comment]
I just noticed `confBufferSize` in the settings, maybe we should be using that instead?

**Comment by FinleyMcIlwaine** [comment]
I have confirmed that the [recent patch to http-semantics](https://github.com/kazu-yamamoto/http-semantics/pull/3) fixes the bus errors/segfaults we saw here when adjusting the window size. I have also confirmed that lowering the window size does indeed lower heap residency in the receiver for our stress test.

The default connection window size in http2 is relatively large (1048576 bytes), so the stress test was is actually limited by the *initial* window size in `Network.HTTP2.H2.Settings.defaultSettings`, which is also a relatively large 262144 bytes. With those default window sizes, in our server streaming RPC stress test, we see this:

<img width="822" alt="Screenshot 2024-06-18 at 5 10 52 PM" src="https://github.com/well-typed/grapesy/assets/43023876/704c4bfc-2449-4845-b2b3-bf33048f5c9b">

Halving that initial window size manually in grapesy with something like this in `connectInsecure`

```haskell
...
          , HTTP2.Client.settings =
              (HTTP2.Client.settings HTTP2.Client.defaultClientConfig)
                { HTTP2.Client.initialWindowSize = 262144 `div` 2
                }
...
```

the residency drops:

<img width="921" alt="Screenshot 2024-06-18 at 5 33 51 PM" src="https://github.com/well-typed/grapesy/assets/43023876/f8b228e2-0b79-41d6-b393-2074911dba7f">

Halving it again:

<img width="915" alt="Screenshot 2024-06-18 at 5 37 11 PM" src="https://github.com/well-typed/grapesy/assets/43023876/c7168c8e-e274-49a5-9f5d-c2f45c2ae542">

So making the http2 window size configurable does seem like it would be a good improvement.

**Comment by edsko** [comment]
Ok, awesome. Good to know that our understanding of the memory behaviour is correct now. Let's add a grapesy flag that allows to set these two parameters, and when we document memory behaviour in the yet-to-be-written manual, we should mention this.

**Comment by edsko** [comment]
Relevant: https://github.com/kazu-yamamoto/http2/issues/121#issuecomment-2177922010

**Comment by edsko** [comment]
We need three parameters to be configurable: max concurrent streams, stream window size, and connection size, and we should also pick our own defaults independent from the defaults from `http2` (or `network-control`).

**Comment by edsko** [comment]
Increasing priority to high due to https://github.com/well-typed/grapesy/issues/169#issuecomment-2203383858 .
