### ISSUE TITLE
Uncaught `KilledByHttp2ThreadManager` exceptions

### ISSUE THREAD

**Issue by edsko** [well-typed/grapesy#156]
When running the test suite, we're getting output such as 

```
Uncaught exception in ThreadId 9542 (unknown label): KilledByHttp2ThreadManager (Just ConnectionIsClosed)
```

(coming from `uncaughtExceptionHandler` in `test-grapesy/Main.hs`). I previously tried to fix this (https://github.com/kazu-yamamoto/http2/pull/92) but something changed somewhere and now we're still seeing these exceptions occassionally. I think it doesn't infer with the functionality of the library, but it's confusing output nonetheless.

**Comment by edsko** [comment]
@FinleyMcIlwaine The threads created by `grapesy` are labelled, but the threads created by `http2` are not. I have a WIP branch at https://github.com/edsko/http2/tree/edsko/thread-labelling to address this. I'm not sure what the status of it is, it for sure needs rebasing, and it might be incomplete.

**Comment by edsko** [comment]
_Possibly_ related: https://github.com/well-typed/grapesy/issues/123#issuecomment-2041043104 (I thought I fixed these though by adding more general functions upstream to `http2` - mentioning it just in case.)

**Comment by FinleyMcIlwaine** [comment]
I am not seeing these messages on `main` anymore after #183

**Comment by edsko** [comment]
We're not seeing this anymore (as of 492c351329bf8e59e983118907e0c1f500576fa1). Closing.
