### ISSUE TITLE
Grapesy server kills client with "too many pings" / "too many empty data"

### ISSUE THREAD

**Issue by edsko** [well-typed/grapesy#177]
Two manifestations:

* When running with a larger window size and more workers, the Java client gets killed by the grapesy server ("too many pings"). Related: https://github.com/kazu-yamamoto/http2/pull/108 .
* Grapesy kvstore (without JSON) against itself, with 16 MB of connection space, crashes with "too many empty data"

**Comment by edsko** [comment]
Suggestions:

* We should up the ping limit again (the Java client sends a lot of pings)
* Maybe to reproduce the "too many empty", we could lower the limit (hardcoded in `http2` currently) and try again; and if we have a better understanding (or maybe even without), we should submit a patch to `http2` to make the limit configurable and raise the default (maybe we should just make _all_ limits configurable).

**Comment by FinleyMcIlwaine** [comment]
I am now seeing the `too many empty data` in the kvstore benchmark ran with

```
cabal run grapesy-kvstore -- --benchmark --no-work-simulation
```

At commit [700138262da29573f45a8344205ee36c50cc0b71](https://github.com/well-typed/grapesy/commits/700138262da29573f45a8344205ee36c50cc0b71) (on `edsko/new-http2-architecture`). It appears to be somewhat non-deterministic, as slowing things down with some intermediate checks/tracing makes it less likely. 

What I have determined so far is that the server is sending empty data frames to the client.

**Comment by FinleyMcIlwaine** [comment]
I believe this can be closed now, fixed by #183

**Comment by edsko** [comment]
Reopening, we're seeing "too many empty data" again.

**Comment by edsko** [comment]
Note: we previously thought we should in principle be able to set the limit for empty `DATA` to zero; this is not the case: this would _only_ be possible for clients and server handlers who know _when_ they send their final message that it is in fact the final message; this is not always true. It also also not true for clients they terminate with an exception, which will result in stream being closed with an empty DATA frame. 

(Perhaps we should consider whether the client can use a low-level HTTP mechanism to indicate to the server that the termination is not "clean"?)

**Comment by FinleyMcIlwaine** [comment]
I have the reproducer on the `finley/177` branch. If you run

```
cabal run test-grapesy -- -p '/Test.Sanity.Exception/'
``` 

You will see the empty data exceptions being printed from `handleException`.

**Comment by edsko** [comment]
I think we realized what was happening here. The test in `Test.Sanity.Exception` starts 100 concurrent calls. As written, due to https://github.com/well-typed/grapesy/issues/209, the server handler that was unlucky enough to deal with the client that throws an exception, would _itself_ terminate with `HandlerTerminated`. Since this is not an "expected exception" in the test suite, _all other_ still ongoing tests would then be killed, resulting in the empty data frames.
