### ISSUE TITLE
Make all `http2` rate limits configurable

### ISSUE THREAD

**Issue by FinleyMcIlwaine** [well-typed/grapesy#188]
`http2` implements rate limits for PINGs, empty data frames, SETTINGS frames, and RST frames. We want to make all of these rate limits configurable in `grapesy`. This is motivated in part by the fact that we want to set a different PING rate limit default after our experience with the Java kvstore JSON client sending enough pings to trigger the `http2` default rate limit (see #177).

**Comment by FinleyMcIlwaine** [comment]
This is waiting on [support in http2-tls](https://github.com/kazu-yamamoto/http2-tls/pull/20). Once that is in and we move to the new http2 server architecture, I will rebase [my `finley/rate-limits`](https://github.com/well-typed/grapesy/tree/finley/rate-limits) branch on `main` and open a PR for full configurability of the rate limits.

**Comment by edsko** [comment]
Closed in #191.
