### ISSUE TITLE
Audit `http2` for uses of `catch` from `unliftio`

### ISSUE THREAD

**Issue by edsko** [well-typed/grapesy#193]
In https://github.com/kazu-yamamoto/http2/pull/92 we changed things so that the `KilledByHttp2ThreadManager` exception would not be remain uncaught, but a later change to `unliftio` meant that [the behaviour of `catch` changed](
https://hackage.haskell.org/package/unliftio-0.2.25.0/docs/UnliftIO-Exception.html#v:catchSyncOrAsync): only synchronous exceptions are caught! We should check all uses of `catch` and friends in `http2`.

**Comment by edsko** [comment]
Chances are good that this will fix #156.

**Comment by FinleyMcIlwaine** [comment]
Searching for `SyncOrAsync` in `unliftio`, only `try`, `catch`, and `handle` have this weird behavior, so they might be the only functions we need to audit usages of.
<img width="627" alt="Screenshot 2024-07-17 at 8 37 10 AM" src="https://github.com/user-attachments/assets/0ca2b244-4eaf-4644-95ea-27b97f36b086">

**Comment by edsko** [comment]
Below is an exhaustive (I think) list of all functions in `unliftio` that require scrutiny; all of these functions intentionally do not deal with asynchronous exceptions. Auditing would take one of two forms:

1. Functions that are polymorphic in the exception type, such as 
    
    ```haskell
    catch         :: (..) => m a -> (e -> m a) -> m a
    catchJust     :: (..) => (e -> Maybe b) -> m a -> (b -> m a) -> m a
    ```

    would depend on how `e` is instantiated; if instantiated to `SomeException`, and the intention is to catch also asynchronous exception, this function cannot be used (`unliftio` offers `catchSyncOrAsync).

2. Functions using `SomeException`, such as 

    ```haskell
    catchAny      :: (..) => m a -> (SomeException -> m a) -> m a
     ```

    need to be audited to see if the intention really is to catch only synchronous exceptions.

The full list:

```haskell
catch         :: (..) => m a -> (e -> m a) -> m a
catchAny      :: (..) => m a -> (SomeException -> m a) -> m a
catchDeep     :: (..) => m a -> (e -> m a) -> m a
catchAnyDeep  :: (..) => m a -> (SomeException -> m a) -> m a
catchJust     :: (..) => (e -> Maybe b) -> m a -> (b -> m a) -> m a

handle        :: (..) => (e -> m a) -> m a -> m a
handleAny     :: (..) => (SomeException -> m a) -> m a -> m a
handleDeep    :: (..) => (e -> m a) -> m a -> m a
handleAnyDeep :: (..) => (SomeException -> m a) -> m a -> m a
handleJust    :: (..) => (e -> Maybe b) -> (b -> m a) -> m a -> m a

try           :: (..) => m a -> m (Either e a)
tryAny        :: (..) => m a -> m (Either SomeException a)
tryDeep       :: (..) => m a -> m (Either e a)
tryAnyDeep    :: (..) => m a -> m (Either SomeException a)
tryJust       :: (..) => (e -> Maybe b) -> m a -> m (Either b a)

pureTry       ::         a -> Either SomeException a
pureTryDeep   :: (..) => a -> Either SomeException a

catches       :: (..) => m a -> [Handler m a] -> m a
catchesDeep   :: (..) => m a -> [Handler m a] -> m a

mapExceptionM :: (..) => (e1 -> e2) -> m a -> m a

catching      :: (..) => Getting (First a) SomeException a -> m r -> (a -> m r) -> m r
catching_     :: (..) => Getting (First a) SomeException a -> m r -> m r -> m r
handling      :: (..) => Getting (First a) SomeException a -> (a -> m r) -> m r -> m r
handling_     :: (..) => Getting (First a) SomeException a -> m r -> m r -> m r
trying        :: (..) => Getting (First a) SomeException a -> m r -> m (Either a r)
trying_       :: (..) => Getting (First a) SomeException a -> m r -> m (Maybe r)
```

**Comment by edsko** [comment]
Report and PR at https://github.com/kazu-yamamoto/http2/pull/138 .
