### ISSUE TITLE
Typo in `Network.GRPC.Common.StreamType` module haddocks

### ISSUE THREAD

**Issue by FinleyMcIlwaine** [well-typed/grapesy#52]
https://github.com/well-typed/grapesy/blob/6f8c0512bfb3bb8ad75f8e9bcdb193a7309d0372/src/Network/GRPC/Common/StreamType.hs#L3

**Comment by edsko** [comment]
Hah, I noticed this at some point to, no idea what went wrong, and unfortunately not even `git` history revealed what this text was ever meant to be :) Addressed by #54, which improves some docs in general.
