### ISSUE TITLE
Stress-test to detect any memory leaks etc.

### ISSUE THREAD

**Issue by edsko** [well-typed/grapesy#60]
The main test suite is concerned with behaviour, not resource usage. We need to have a serious stress test, making thousands and thousands of connections, and thousands and thousands of calls on each connection, and verify that no resources get leaked. Might perhaps be useful to limit the heap and the stack size when we run these tests.

May require some changes to `http2`; see discussion in https://github.com/kazu-yamamoto/http2/pull/78 .

**Comment by FinleyMcIlwaine** [comment]
Implemented part of this at #134, still need to implement the `many-messages` stress test. We also should stress test a situation where many reconnections happen.

**Comment by edsko** [comment]
We also need to add a test to reproduce #169 here.

**Comment by edsko** [comment]
When we close this issue, there are a few references to this ticket in the codebase that we should check and, if indeed handled, delete.
